# Generated by Django 4.0.6 on 2023-12-09 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerAchieves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.IntegerField(default=0)),
                ('health', models.IntegerField(default=100)),
                ('points', models.IntegerField(default=0)),
                ('completion_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('login', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('achieves', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.playerachieves')),
            ],
        ),
    ]
